### ISSUE TITLE
Use Puppeteer's own test expectations file

### ISSUE THREAD

**Issue by whimboo** [puppeteer/ispuppeteerwebdriverbidiready#13]
Since the Puppeteer 17.1.3 release Puppeteer has a new expectation file:
https://github.com/puppeteer/puppeteer/blob/main/test/TestExpectations.json

Given that we consider dropping our own expectation file, which is currently used to build the data for ispuppeteerfirefoxready, the code in this repository should probably use the Puppeteer's own file.

@mathiasbynens what do you think? Should we change it, or maybe abandon this page? After talking to @OrKoN he had the idea with ispuppeteerbidiready instead.

**Comment by mathiasbynens** [comment]
I like the idea of pivoting to `ispuppeteerbidiready`!

**Comment by whimboo** [comment]
Great. So shall we have a new repository for that, or how would like like to see this change?

Note that we want to vendor in the recent Puppeteer changes ans by doing so the expectation file this tool is reading from will no longer be available.

**Comment by OrKoN** [comment]
We could perhaps rename this repository and change the implementation to fetch data from a new source? we need to see where we can store the data.

**Comment by OrKoN** [comment]
Renamed and used Puppeteer's data for the website.

**Comment by OrKoN** [comment]
We don't have any Chrome data yet.
