### ISSUE TITLE
Annotate each value

### ISSUE THREAD

**Issue by mathiasbynens** [puppeteer/ispuppeteerwebdriverbidiready#8]
Ideally the individual values in the chart can be viewed by hovering over each data point, similar to how it's done here: https://mathiasbynens.be/demo/jquery-size

**Comment by Bilal-io** [comment]
I cloned the repo to make this work, but to my surprise it already does. But the devs are intentionally removing any JavaScript from being during the build process.

```Javascript
  await page.evaluate(() => {
    const scripts = document.querySelectorAll('script');
    for (const script of scripts) {
      script.remove();
    }
  });
```

**Comment by mathiasbynens** [comment]
@Bilal-io Thanks for taking a look! The reason for that snippet is that we want to produce a minimal HTML page with as little JS as possible in the end. I guess we need to keep at least some JS if we want this to work, which is unfortunate.

**Comment by Bilal-io** [comment]
Hey @mathiasbynens I have attempted to keep the loader.js script in the HTML by adding `class="keep"` to the script element, and then wrap `script.remove()` in a conditional statement `if (script.className !== 'keep')` but unfortunately it seems like main.js file is also needed if I am not mistaken.
This will require a few more changes.

**Comment by OrKoN** [comment]
Added HTML annotations
